# Generated by Django 5.1.2 on 2024-10-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='failure_date',
            field=models.DateField(blank=True, default='2024-01-01', null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='operating_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
