# Generated by Django 5.1.2 on 2024-10-11 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_machine_client_alter_machine_service_company'),
        ('reclamations', '0003_reclamation_failure_date_reclamation_operating_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_company_reclamations', to='machines.reference'),
        ),
    ]
