# Generated by Django 5.1.2 on 2024-10-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('engine_serial_number', models.CharField(max_length=255)),
                ('transmission_serial_number', models.CharField(max_length=255)),
                ('driving_bridge_serial_number', models.CharField(max_length=255)),
                ('controlled_bridge_serial_number', models.CharField(max_length=255)),
                ('contract_number_date', models.CharField(max_length=255)),
                ('shipment_date', models.DateField()),
                ('consignee', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('configuration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
