# Generated by Django 5.1.2 on 2024-10-09 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_machines', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_company_machines', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='machine',
            name='controlled_bridge_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_bridge_models', to='machines.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='driving_bridge_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driving_bridge_models', to='machines.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engine_models', to='machines.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='machines.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmission_models', to='machines.reference'),
        ),
    ]
